// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/contact.tsx";
import * as $2 from "./routes/illustrations.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/nature-emois.tsx";
import * as $5 from "./routes/nebula.tsx";
import * as $6 from "./routes/neopace.tsx";
import * as $7 from "./routes/nuevo-mundo.tsx";
import * as $8 from "./routes/on-fleek.tsx";
import * as $9 from "./routes/pok.tsx";
import * as $10 from "./routes/salsa-loca.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/contact.tsx": $1,
    "./routes/illustrations.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/nature-emois.tsx": $4,
    "./routes/nebula.tsx": $5,
    "./routes/neopace.tsx": $6,
    "./routes/nuevo-mundo.tsx": $7,
    "./routes/on-fleek.tsx": $8,
    "./routes/pok.tsx": $9,
    "./routes/salsa-loca.tsx": $10,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
